-- Web Push subscriptions for admin PWA notifications.

create table if not exists public.web_push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  store_id int not null references public.stores (id),
  user_id uuid,
  user_agent text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists web_push_subscriptions_store_idx
  on public.web_push_subscriptions (store_id)
  where is_active = true;

alter table public.web_push_subscriptions enable row level security;

drop policy if exists "anon_all_web_push_subscriptions" on public.web_push_subscriptions;
create policy "anon_all_web_push_subscriptions" on public.web_push_subscriptions
  for all to anon using (true) with check (true);

drop policy if exists "auth_all_web_push_subscriptions" on public.web_push_subscriptions;
create policy "auth_all_web_push_subscriptions" on public.web_push_subscriptions
  for all to authenticated using (true) with check (true);

