-- Registro explícito de ajustes de caja por corte (faltante/sobrante/balanceado).

create table if not exists public.shift_cash_adjustments (
  id bigint generated by default as identity primary key,
  shift_closure_id int not null references public.shift_closures (id) on delete cascade,
  shift_id int not null references public.shifts (id) on delete cascade,
  recorded_at timestamptz not null default now(),
  adjustment_type text not null
    check (adjustment_type in ('shortage', 'surplus', 'balanced')),
  amount numeric not null default 0,
  signed_amount numeric not null default 0
);

create index if not exists shift_cash_adjustments_shift_time_idx
  on public.shift_cash_adjustments (shift_id, recorded_at desc);

alter table public.shift_cash_adjustments enable row level security;

drop policy if exists "anon_all_shift_cash_adjustments" on public.shift_cash_adjustments;
create policy "anon_all_shift_cash_adjustments" on public.shift_cash_adjustments
  for all to anon using (true) with check (true);

drop policy if exists "auth_all_shift_cash_adjustments" on public.shift_cash_adjustments;
create policy "auth_all_shift_cash_adjustments" on public.shift_cash_adjustments
  for all to authenticated using (true) with check (true);

